// <auto-generated />
namespace VideoRentalApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Restart02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Restart02));
        
        string IMigrationMetadata.Id
        {
            get { return "202210160423039_Restart02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
